name: sau
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.1.0+1
  path: ^1.8.3
  path_provider: ^2.0.11
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^9.3.2
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.0.9
  video_player: ^2.3.0
  http: ^1.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
